FROM python:latest

COPY setup/pip_requirements.txt /setup/pip_requirements.txt

RUN pip install --no-cache-dir --upgrade -r /setup/pip_requirements.txt

COPY src /src

WORKDIR /src

EXPOSE 80

CMD ["python", "-m", "app"]